# Generated by Django 5.2.7 on 2025-11-04 00:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(default='Get in touch with our procurement engineering team', help_text='Contact page introduction', max_length=500)),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Additional contact information')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('address', wagtail.fields.RichTextField(blank=True, help_text='Physical address')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EquipmentCategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, help_text='Brief introduction to this equipment category', max_length=500)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Detailed description of equipment category')),
                ('key_features', wagtail.fields.RichTextField(blank=True, help_text='Key features and benefits')),
                ('typical_applications', wagtail.fields.RichTextField(blank=True, help_text='Typical applications and use cases')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EquipmentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, help_text='Equipment subtitle or model info', max_length=255)),
                ('description', wagtail.fields.RichTextField(help_text='Full equipment description')),
                ('specifications', wagtail.fields.RichTextField(blank=True, help_text='Technical specifications')),
                ('applications', wagtail.fields.RichTextField(blank=True, help_text='Applications and use cases')),
                ('industries', wagtail.fields.RichTextField(blank=True, help_text='Industries this equipment serves')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='IndustryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, help_text='Brief industry introduction', max_length=500)),
                ('description', wagtail.fields.RichTextField(help_text='Detailed industry description')),
                ('expertise', wagtail.fields.RichTextField(blank=True, help_text='Our expertise in this industry')),
                ('equipment_provided', wagtail.fields.RichTextField(blank=True, help_text='Types of equipment we provide to this industry')),
                ('client_examples', wagtail.fields.RichTextField(blank=True, help_text='Example clients or projects')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, help_text='Brief introduction or tagline', max_length=500)),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Main page content')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description',
            field=wagtail.fields.RichTextField(default='Providing quality equipment procurement solutions to government facilities, national parks, energy sectors, and municipal services.', help_text='Hero description text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(default='20+ Years of Supply Chain Expertise', help_text='Hero subtitle', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Procurement Engineering Excellence', help_text='Main hero title', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_section',
            field=wagtail.fields.RichTextField(blank=True, help_text='Introduction section below hero'),
        ),
    ]
