# Generated by Django 5.2.7 on 2025-11-04 14:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactpage_equipmentcategorypage_equipmentpage_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='intro',
            field=models.CharField(default='Get in touch with our supply chain engineering team', help_text='Contact page introduction', max_length=500),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_description',
            field=wagtail.fields.RichTextField(default='Delivering quality equipment solutions to government facilities, national parks, energy sectors, and municipal services nationwide.', help_text='Hero description text'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Supply Chain Engineering Excellence', help_text='Main hero title', max_length=255),
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Manufacturer name', max_length=255)),
                ('website', models.URLField(blank=True, help_text='Manufacturer website URL')),
                ('description', models.TextField(blank=True, help_text='Brief description of the manufacturer')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this manufacturer on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ForeignKey(blank=True, help_text='Manufacturer logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
