# Generated by Django 5.2.7 on 2025-11-30 12:37

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contactsubmission_remove_contactpage_from_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederalSupplyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=4, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(db_index=True, max_length=2)),
                ('group_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Federal Supply Class',
                'verbose_name_plural': 'Federal Supply Classes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='NSNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsn', models.CharField(db_index=True, max_length=16, unique=True)),
                ('niin', models.CharField(db_index=True, max_length=9)),
                ('item_name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rep_office', models.CharField(blank=True, max_length=255, verbose_name='Representative Office')),
                ('unit_of_issue', models.CharField(blank=True, max_length=10, verbose_name='Unit of Issue')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('aac', models.CharField(blank=True, max_length=10, verbose_name='AAC')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fsc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='home.federalsupplyclass')),
            ],
            options={
                'verbose_name': 'NSN Item',
                'verbose_name_plural': 'NSN Items',
                'ordering': ['nsn'],
                'indexes': [models.Index(fields=['nsn'], name='home_nsnite_nsn_b3191b_idx'), models.Index(fields=['niin'], name='home_nsnite_niin_b4dbce_idx'), models.Index(fields=['item_name'], name='home_nsnite_item_na_201b43_idx'), models.Index(fields=['fsc', 'item_name'], name='home_nsnite_fsc_id_cb9adf_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='home_nsnite_search__a16fe9_gin')],
            },
        ),
    ]
