# Generated by Django 5.2.7 on 2026-03-03 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_federalsupplyclass_nsnitem'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero background image (1920x600px recommended)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='equipmentcategorypage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero background image (1920x600px recommended)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='equipmentpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero background image (1920x600px recommended)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero background image (1920x900px recommended)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='industrypage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero background image (1920x600px recommended)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero background image (1920x600px recommended)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
