# Generated by Django 5.2.7 on 2026-03-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contactpage_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='cage_code',
            field=models.CharField(blank=True, db_index=True, help_text='CAGE code linking to procurement data', max_length=5),
        ),
    ]
