# Generated by Django 5.2.7 on 2026-03-05 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_manufacturer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NSNItem',
        ),
    ]
