# Generated by Django 5.2.7 on 2026-03-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['company_name'], 'verbose_name': 'Manufacturer', 'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('manufacturer', 'part_number')},
        ),
    ]
