# Generated by Django 5.2.7 on 2026-03-05 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_organization_manufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturerprofile',
            options={'ordering': ['display_order', 'organization__company_name'], 'verbose_name': 'Manufacturer Profile', 'verbose_name_plural': 'Manufacturer Profiles'},
        ),
    ]
