# Generated by Django 5.2.7 on 2026-03-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_tristate_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.SmallIntegerField(choices=[(-1, 'Disabled'), (0, 'Neutral'), (1, 'Enabled')], db_index=True, default=0),
        ),
    ]
