# Generated by Django 5.2.7 on 2026-03-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_default_neutral'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_name',
            field=models.CharField(blank=True, help_text='Natural-language product name (auto-generated, manually overridable)', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, help_text='Title-cased nomenclature (auto-generated from import)', max_length=500),
        ),
    ]
