# Generated by Django 5.2.7 on 2026-03-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FLISVCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niin', models.CharField(db_index=True, max_length=9)),
                ('mrc', models.CharField(max_length=10)),
                ('mode_code', models.CharField(blank=True, max_length=1)),
                ('coded_reply', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'catalog_flisv_characteristic',
                'indexes': [models.Index(fields=['niin'], name='catalog_fli_niin_591a49_idx')],
            },
        ),
    ]
