# Generated by Django 5.2.7 on 2026-03-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_flisv_characteristic_staging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flisvcharacteristic',
            name='coded_reply',
            field=models.TextField(),
        ),
    ]
