# Generated by Django 5.2.7 on 2026-03-13 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_flisv_coded_reply_textfield'),
        ('home', '0011_delete_nsnitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalStockNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsn', models.CharField(db_index=True, max_length=16, unique=True)),
                ('niin', models.CharField(blank=True, db_index=True, max_length=9)),
                ('nomenclature', models.CharField(blank=True, max_length=500)),
                ('unit_of_issue', models.CharField(blank=True, max_length=20)),
                ('is_active', models.SmallIntegerField(choices=[(-1, 'Disabled'), (0, 'Neutral'), (1, 'Enabled')], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fsc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nsns', to='home.federalsupplyclass')),
            ],
            options={
                'verbose_name': 'National Stock Number',
                'verbose_name_plural': 'National Stock Numbers',
                'db_table': 'catalog_nsn',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='nsn_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.nationalstocknumber'),
        ),
        migrations.AddIndex(
            model_name='nationalstocknumber',
            index=models.Index(fields=['fsc'], name='catalog_nsn_fsc_id_cb2080_idx'),
        ),
        migrations.AddIndex(
            model_name='nationalstocknumber',
            index=models.Index(fields=['niin'], name='catalog_nsn_niin_f2f894_idx'),
        ),
    ]
