# Generated by Django 5.2.7 on 2026-03-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_remove_denormalized_nsn_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FLISVCharacteristic',
        ),
        migrations.RemoveIndex(
            model_name='nationalstocknumber',
            name='catalog_nsn_fsc_id_cb2080_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_search__6e8905_gin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_vector',
        ),
        migrations.AlterField(
            model_name='nationalstocknumber',
            name='niin',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='nationalstocknumber',
            name='nsn',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='group',
            field=models.CharField(help_text='Category: Dimensions, Electrical, Material, etc.', max_length=100),
        ),
    ]
