# Generated by Django 5.2.7 on 2026-03-14 00:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_optimize_indexes_drop_staging'),
        ('home', '0011_delete_nsnitem'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nationalstocknumber',
            name='catalog_nsn_niin_f2f894_idx',
        ),
        migrations.AlterUniqueTogether(
            name='pipelinefilter',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='resolved_from_api',
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='cage_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='is_manufacturer',
            field=models.SmallIntegerField(choices=[(-1, 'No'), (0, 'Neutral'), (1, 'Yes')], default=0, help_text='Verified manufacturer? -1=No, 0=Unverified, 1=Yes'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='resolution_status',
            field=models.CharField(choices=[('unresolved', 'Unresolved'), ('sam_gov', 'SAM.gov'), ('highergov', 'HigherGov'), ('cage_file', 'CAGE File'), ('manual', 'Manual')], default='unresolved', max_length=20),
        ),
        migrations.AlterField(
            model_name='manufacturerprofile',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Disabled'), (0, 'Neutral'), (1, 'Enabled')], default=0),
        ),
        migrations.AlterField(
            model_name='nationalstocknumber',
            name='is_active',
            field=models.SmallIntegerField(choices=[(-1, 'Disabled'), (0, 'Neutral'), (1, 'Enabled')], default=0),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('is_active__gte', 0)), fields=['manufacturer'], name='catalog_prod_publishable'),
        ),
        migrations.AddConstraint(
            model_name='manufacturer',
            constraint=models.CheckConstraint(condition=models.Q(('is_manufacturer__in', [-1, 0, 1])), name='catalog_organization_is_manufacturer_valid'),
        ),
        migrations.AddConstraint(
            model_name='manufacturerprofile',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', [-1, 0, 1])), name='catalog_organizationprofile_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='nationalstocknumber',
            constraint=models.CheckConstraint(condition=models.Q(('is_active__in', [-1, 0, 1])), name='catalog_nsn_is_active_valid'),
        ),
        migrations.AddConstraint(
            model_name='pipelinefilter',
            constraint=models.UniqueConstraint(fields=('field_type', 'field_value', 'stage'), name='catalog_pipelinefilter_type_val_stage_uniq'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'part_number'), name='catalog_product_mfr_partnum_uniq'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('is_active__in', [-1, 0, 1])), name='catalog_product_is_active_valid'),
        ),
        # Drop orphan _like indexes left behind by db_index removal
        migrations.RunSQL(
            "DROP INDEX IF EXISTS catalog_organization_resolution_status_33ad0d2e_like;",
            migrations.RunSQL.noop,
        ),
        # Truncate archived pipeline logs (25.6K rows, ~4 MB, Mar 5-7 only)
        migrations.RunSQL(
            "TRUNCATE TABLE catalog_importjoblog;",
            migrations.RunSQL.noop,
        ),
    ]
