# Generated by Django 5.2.7 on 2026-03-14 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_trigram_indexes'),
        ('home', '0011_delete_nsnitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalstocknumber',
            name='fsc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nsns', to='home.federalsupplyclass'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nsn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.nationalstocknumber'),
        ),
    ]
