# Generated by Django 5.2.7 on 2026-03-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_nationalstocknumber_fsc_alter_product_nsn'),
        ('home', '0011_delete_nsnitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederalSupplyClass',
            fields=[
            ],
            options={
                'verbose_name': 'Federal Supply Class',
                'verbose_name_plural': 'Federal Supply Classes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.federalsupplyclass',),
        ),
    ]
