"""Populate FederalSupplyClass name and group_name fields from federal reference data."""

from django.core.management.base import BaseCommand
from home.models import FederalSupplyClass


# Federal Supply Groups (2-digit FSG)
FSG_NAMES = {
    "10": "Weapons",
    "11": "Nuclear Ordnance",
    "12": "Fire Control Equipment",
    "13": "Ammunition and Explosives",
    "14": "Guided Missiles",
    "15": "Aircraft and Airframe Structural Components",
    "16": "Aircraft Components and Accessories",
    "17": "Aircraft Launch, Landing, and Ground Handling Equipment",
    "18": "Space Vehicles",
    "19": "Ships, Small Craft, Pontoons, and Floating Docks",
    "20": "Ship and Marine Equipment",
    "22": "Railway Equipment",
    "23": "Ground Effect Vehicles, Motor Vehicles, Trailers, and Cycles",
    "24": "Tractors",
    "25": "Vehicular Equipment Components",
    "26": "Tires and Tubes",
    "28": "Engines, Turbines, and Components",
    "29": "Engine Accessories",
    "30": "Mechanical Power Transmission Equipment",
    "31": "Bearings",
    "32": "Woodworking Machinery and Equipment",
    "34": "Metalworking Machinery",
    "35": "Service and Trade Equipment",
    "36": "Special Industry Machinery",
    "37": "Agricultural Machinery and Equipment",
    "38": "Construction, Mining, Excavating, and Highway Equipment",
    "39": "Materials Handling Equipment",
    "40": "Rope, Cable, Chain, and Fittings",
    "41": "Refrigeration, Air Conditioning, and Air Circulating Equipment",
    "42": "Fire Fighting, Rescue, and Safety Equipment",
    "43": "Pumps and Compressors",
    "44": "Furnace, Steam Plant, and Drying Equipment",
    "45": "Plumbing, Heating, and Waste Disposal Equipment",
    "46": "Water Purification and Sewage Treatment Equipment",
    "47": "Pipe, Tubing, Hose, and Fittings",
    "48": "Valves",
    "49": "Maintenance and Repair Shop Equipment",
    "51": "Hand Tools",
    "52": "Measuring Tools",
    "53": "Hardware and Abrasives",
    "54": "Prefabricated Structures and Scaffolding",
    "55": "Lumber, Millwork, Plywood, and Veneer",
    "56": "Construction and Building Materials",
    "58": "Communication, Detection, and Coherent Radiation Equipment",
    "59": "Electrical and Electronic Equipment Components",
    "60": "Fiber Optics Materials, Components, Assemblies, and Accessories",
    "61": "Electric Wire, and Power and Distribution Equipment",
    "62": "Lighting Fixtures and Lamps",
    "63": "Alarm, Signal, and Security Detection Systems",
    "65": "Medical, Dental, and Veterinary Equipment and Supplies",
    "66": "Instruments and Laboratory Equipment",
    "67": "Photographic Equipment",
    "68": "Chemicals and Chemical Products",
    "69": "Training Aids and Devices",
    "70": "Automatic Data Processing Equipment",
    "71": "Furniture",
    "72": "Household and Commercial Furnishings and Appliances",
    "73": "Food Preparation and Serving Equipment",
    "74": "Office Machines and Visible Record Equipment",
    "75": "Office Supplies and Devices",
    "76": "Books, Maps, and Other Publications",
    "77": "Musical Instruments, Phonographs, and Home Radios",
    "78": "Recreational and Athletic Equipment",
    "79": "Cleaning Equipment and Supplies",
    "80": "Brushes, Paints, Sealers, and Adhesives",
    "81": "Containers, Packaging, and Packing Supplies",
    "83": "Textiles, Leather, Furs, Apparel and Shoe Findings",
    "84": "Clothing, Individual Equipment, and Insignia",
    "85": "Toiletries",
    "87": "Agricultural Supplies",
    "88": "Live Animals",
    "89": "Subsistence",
    "91": "Fuels, Lubricants, Oils, and Waxes",
    "93": "Nonmetallic Fabricated Materials",
    "94": "Nonmetallic Crude Materials",
    "95": "Metal Bars, Sheets, and Shapes",
    "96": "Ores, Minerals, and Their Primary Products",
    "99": "Miscellaneous",
}

# Federal Supply Classes (4-digit FSC)
FSC_NAMES = {
    "1005": "Guns, through 30mm",
    "1010": "Guns, over 30mm up to 75mm",
    "1015": "Guns, 75mm through 125mm",
    "1020": "Guns, over 125mm through 150mm",
    "1025": "Guns, over 150mm through 200mm",
    "1030": "Guns, over 200mm through 300mm",
    "1035": "Guns, over 300mm",
    "1040": "Chemical Weapons and Equipment",
    "1045": "Launchers, Torpedo and Depth Charge",
    "1055": "Launchers, Grenade",
    "1070": "Pyrotechnics",
    "1075": "Degaussing and Mine Sweeping Equipment",
    "1080": "Camouflage and Deception Equipment",
    "1090": "Assemblies Interchangeable Between Weapons",
    "1095": "Miscellaneous Weapons",
    "1105": "Nuclear Bombs",
    "1110": "Nuclear Projectiles",
    "1115": "Nuclear Warheads and Warhead Sections",
    "1120": "Nuclear Depth Charges",
    "1125": "Nuclear Demolition Charges",
    "1127": "Nuclear Rockets",
    "1130": "Conversion Kits, Nuclear Ordnance",
    "1135": "Fuzing and Firing Devices, Nuclear Ordnance",
    "1140": "Nuclear Components",
    "1145": "Explosive and Pyrotechnic Components, Nuclear Ordnance",
    "1190": "Specialized Test and Handling Equipment, Nuclear Ordnance",
    "1195": "Miscellaneous Nuclear Ordnance",
    "1210": "Fire Control Directors",
    "1220": "Fire Control Computing Sights and Devices",
    "1230": "Fire Control Systems, Complete",
    "1240": "Optical Sighting and Ranging Equipment",
    "1250": "Fire Control Stabilizing Mechanisms",
    "1260": "Fire Control Designating and Indicating Equipment",
    "1265": "Fire Control Transmitting and Receiving Equipment, except Airborne",
    "1270": "Aircraft Gunnery Fire Control Components",
    "1280": "Aircraft Bombing Fire Control Components",
    "1285": "Fire Control Radar Equipment, except Airborne",
    "1287": "Fire Control Sonar Equipment",
    "1290": "Fire Control Components",
    "1295": "Miscellaneous Fire Control Equipment",
    "1305": "Ammunition, through 30mm",
    "1310": "Ammunition, over 30mm up to 75mm",
    "1315": "Ammunition, 75mm through 125mm",
    "1320": "Ammunition, over 125mm",
    "1325": "Bombs",
    "1330": "Grenades",
    "1336": "Guided Missile Warheads and Explosive Components",
    "1337": "Guided Missile and Space Vehicle Explosive Propulsion Units",
    "1338": "Guided Missile and Space Vehicle Inert Propulsion Units",
    "1340": "Rockets and Rocket Ammunition",
    "1345": "Land Mines",
    "1350": "Underwater Mine and Torpedo Components",
    "1355": "Torpedoes and Components",
    "1360": "Depth Charge and Underwater Mine Components",
    "1365": "Military Chemical Agents",
    "1370": "Pyrotechnics and Fireworks",
    "1375": "Demolition Materials",
    "1376": "Bulk Explosives",
    "1377": "Cartridge and Propellant Actuated Devices and Components",
    "1380": "Military Biological Agents",
    "1385": "Surface Use Explosive Ordnance Disposal Tools and Equipment",
    "1386": "Underwater Explosive Ordnance Disposal Tools and Equipment",
    "1390": "Fuzes and Primers",
    "1395": "Miscellaneous Ammunition",
    "1398": "Specialized Ammunition Handling and Servicing Equipment",
    "1410": "Guided Missiles",
    "1420": "Guided Missile Components",
    "1425": "Guided Missile Systems, Complete",
    "1427": "Guided Missile Subsystems",
    "1430": "Guided Missile Remote Control Systems",
    "1440": "Launchers, Guided Missile",
    "1450": "Guided Missile Handling and Servicing Equipment",
    "1510": "Aircraft, Fixed Wing",
    "1520": "Aircraft, Rotary Wing",
    "1540": "Gliders",
    "1550": "Drones",
    "1560": "Airframe Structural Components",
    "1610": "Aircraft Propellers and Components",
    "1615": "Helicopter Rotor Blades, Drive Mechanisms, and Components",
    "1620": "Aircraft Landing Gear Components",
    "1630": "Aircraft Wheel and Brake Systems",
    "1640": "Aircraft Control Surfaces",
    "1650": "Hydraulic, Vacuum, and De-Icing System Components",
    "1660": "Air Conditioning, Heating, and Pressurizing Equipment",
    "1670": "Parachutes; Aerial Pick Up, Delivery, Recovery Systems",
    "1680": "Miscellaneous Aircraft Accessories and Components",
    "1710": "Aircraft Launching Equipment",
    "1720": "Aircraft Landing Equipment",
    "1730": "Aircraft Ground Servicing Equipment",
    "1740": "Airfield Specialized Trucks and Trailers",
    "1810": "Space Vehicles",
    "1820": "Space Vehicle Components",
    "1830": "Space Vehicle Remote Control Systems",
    "1840": "Space Vehicle Launchers",
    "1850": "Space Vehicle Handling and Servicing Equipment",
    "1905": "Combat Ships and Landing Vessels",
    "1910": "Transport Vessels",
    "1915": "Special Service Vessels",
    "1920": "Tugs, Barges, and Lighters",
    "1925": "Special Boats",
    "1930": "Barges and Lighters, Special Purpose",
    "1935": "Floating Drydocks",
    "1940": "Small Craft",
    "1945": "Pontoons and Floating Docks",
    "1950": "Torpedoes, Mines, Depth Charges, Demolition",
    "1990": "Miscellaneous Ships, Small Craft, and Pontoons",
    "2010": "Ship and Boat Propulsion Components",
    "2020": "Rigging and Rigging Gear",
    "2030": "Deck Machinery",
    "2040": "Marine Hardware and Hull Items",
    "2050": "Buoys",
    "2060": "Anchors, Anchor Chain and Accessories",
    "2090": "Miscellaneous Ship and Marine Equipment",
    "2210": "Locomotives",
    "2220": "Rail Cars",
    "2230": "Right-of-Way Construction and Maintenance Equipment, Railroad",
    "2240": "Locomotive and Rail Car Accessories and Components",
    "2250": "Track Material, Railroad",
    "2290": "Miscellaneous Railway Equipment",
    "2305": "Ground Effect Vehicles",
    "2310": "Passenger Motor Vehicles",
    "2320": "Trucks and Truck Tractors, Wheeled",
    "2330": "Trailers",
    "2340": "Motorcycles, Motor Scooters, and Bicycles",
    "2350": "Combat, Assault, and Tactical Vehicles, Tracked",
    "2355": "Combat, Assault, and Tactical Vehicles, Wheeled",
    "2410": "Tractors, Full Tracked, Low Speed",
    "2420": "Tractors, Wheeled",
    "2430": "Tractors, Full Tracked, High Speed",
    "2510": "Vehicular Cab, Body, and Frame Structural Components",
    "2520": "Vehicular Power Transmission Components",
    "2530": "Vehicular Brake, Steering, Axle, Wheel, and Track Components",
    "2540": "Vehicular Furniture and Accessories",
    "2590": "Miscellaneous Vehicular Components",
    "2610": "Tires and Tubes, Pneumatic, except Aircraft",
    "2620": "Tires and Tubes, Pneumatic, Aircraft",
    "2630": "Tires, Solid and Cushion",
    "2640": "Tire Rebuilding and Tire and Tube Repair Materials",
    "2810": "Gasoline Reciprocating Engines and Components",
    "2815": "Diesel Engines and Components",
    "2820": "Steam Engines, Reciprocating",
    "2825": "Steam Turbines and Components",
    "2830": "Water Turbines and Water Wheels",
    "2835": "Gas Turbines and Jet Engines, Aircraft",
    "2840": "Gas Turbines and Jet Engines, Non-Aircraft",
    "2845": "Rocket Engines",
    "2895": "Miscellaneous Engines and Components",
    "2910": "Engine Fuel System Components, Non-Aircraft",
    "2915": "Engine Fuel System Components, Aircraft",
    "2920": "Engine Electrical System Components, Non-Aircraft",
    "2925": "Engine Electrical System Components, Aircraft",
    "2930": "Engine Cooling System Components, Non-Aircraft",
    "2935": "Engine Cooling System Components, Aircraft",
    "2940": "Engine Air and Oil Filters, Strainers, and Cleaners",
    "2945": "Engine Air and Oil Filters, Strainers, Cleaners, Aircraft",
    "2950": "Turbosuperchargers",
    "2990": "Miscellaneous Engine Accessories, Non-Aircraft",
    "2995": "Miscellaneous Engine Accessories, Aircraft",
    "3010": "Torque Converters and Speed Changers",
    "3020": "Gears, Pulleys, Sprockets, and Transmission Chain",
    "3030": "Belting, Drive Belts, Fan Belts, and Accessories",
    "3040": "Miscellaneous Power Transmission Equipment",
    "3110": "Bearings, Antifriction, Unmounted",
    "3120": "Bearings, Plain, Unmounted",
    "3130": "Bearings, Mounted",
    "3210": "Sawmill and Planing Mill Machinery",
    "3220": "Woodworking Machines",
    "3230": "Tools and Attachments for Woodworking Machinery",
    "3405": "Saws and Filing Machines",
    "3408": "Machining Centers and Way-Type Machines",
    "3410": "Electrical and Ultrasonic Erosion Machines",
    "3411": "Boring Machines",
    "3412": "Broaching Machines",
    "3413": "Drilling and Tapping Machines",
    "3414": "Gear Cutting and Finishing Machines",
    "3415": "Grinding Machines",
    "3416": "Lathes",
    "3417": "Milling Machines",
    "3418": "Planers and Shapers",
    "3419": "Miscellaneous Machine Tools",
    "3422": "Rolling Mills and Drawing Machines",
    "3424": "Metal Heat Treating and Non-Thermal Treating Equipment",
    "3426": "Metal Finishing Equipment",
    "3431": "Electric Arc Welding Equipment",
    "3432": "Electric Resistance Welding Equipment",
    "3433": "Gas Welding, Heat Cutting, and Metalizing Equipment",
    "3436": "Welding Positioners and Manipulators",
    "3438": "Miscellaneous Welding Equipment",
    "3439": "Miscellaneous Welding, Soldering, and Brazing Supplies",
    "3441": "Bending and Forming Machines",
    "3442": "Hydraulic and Pneumatic Presses, Power Driven",
    "3443": "Mechanical Presses, Power Driven",
    "3444": "Manual Presses",
    "3445": "Punching and Shearing Machines",
    "3446": "Forging Machinery and Hammers",
    "3447": "Wire and Metal Ribbon Forming Machines",
    "3448": "Riveting Machines",
    "3449": "Miscellaneous Secondary Metal Forming and Cutting Machines",
    "3450": "Machine Tools, Portable",
    "3455": "Cutting Tools for Machine Tools",
    "3460": "Machine Tool Accessories",
    "3461": "Jigs, Fixtures, and Templates",
    "3465": "Production Jigs, Fixtures, and Templates",
    "3470": "Machine Shop Sets, Kits, and Outfits",
    "3510": "Laundry and Dry Cleaning Equipment",
    "3520": "Shoe Repairing Equipment",
    "3530": "Industrial Sewing Machines and Mobile Textile Repair Shops",
    "3540": "Wrapping and Packaging Machinery",
    "3550": "Vending and Coin Operated Machines",
    "3590": "Miscellaneous Service and Trade Equipment",
    "3605": "Food Products Machinery and Equipment",
    "3610": "Printing, Duplicating, and Bookbinding Equipment",
    "3611": "Industrial Marking Machines",
    "3615": "Pulp and Paper Industries Machinery",
    "3620": "Rubber and Plastics Working Machinery",
    "3625": "Textile Industries Machinery",
    "3630": "Clay and Concrete Products Industries Machinery",
    "3635": "Crystal and Glass Industries Machinery",
    "3640": "Tobacco Manufacturing Machinery",
    "3645": "Leather Tanning and Leather Working Machinery",
    "3650": "Chemical and Pharmaceutical Products Manufacturing Machinery",
    "3655": "Gas Generating and Dispensing Systems, Fixed or Mobile",
    "3660": "Industrial Size Reduction Machinery",
    "3670": "Oil Refining Machinery",
    "3680": "Foundry Machinery, Related Equipment, and Supplies",
    "3685": "Specialized Metal Container Manufacturing Machinery",
    "3690": "Specialized Manufacturing Machinery",
    "3693": "Industrial Assembly Machines",
    "3694": "Clean Work Stations, Controlled Environment, and Related Equipment",
    "3695": "Miscellaneous Special Industry Machinery",
    "3710": "Soil Preparation Equipment",
    "3720": "Harvesting Equipment",
    "3730": "Dairy, Poultry, and Livestock Equipment",
    "3740": "Pest, Disease, and Frost Control Equipment",
    "3750": "Gardening Implements and Tools",
    "3770": "Saddlery, Harness, Whips, and Related Animal Furnishings",
    "3805": "Earth Moving and Excavating Equipment",
    "3810": "Cranes and Crane-Shovels",
    "3815": "Crane and Crane-Shovel Attachments",
    "3820": "Mining, Rock Drilling, Earth Boring, and Related Equipment",
    "3825": "Road Clearing, Cleaning, and Marking Equipment",
    "3830": "Truck and Tractor Attachments",
    "3835": "Petroleum Production and Distribution Equipment",
    "3895": "Miscellaneous Construction Equipment",
    "3910": "Conveyors",
    "3920": "Material Handling Equipment, Nonself-Propelled",
    "3930": "Warehouse Trucks and Tractors, Self-Propelled",
    "3940": "Blocks, Tackle, Rigging, and Slings",
    "3950": "Winches, Hoists, and Cranes",
    "3960": "Elevators and Escalators",
    "3990": "Miscellaneous Materials Handling Equipment",
    "4010": "Chain and Wire Rope",
    "4020": "Fiber Rope, Cordage, and Twine",
    "4030": "Fittings for Rope, Cable, and Chain",
    "4110": "Refrigeration Equipment",
    "4120": "Air Conditioning Equipment",
    "4130": "Compressors and Vacuum Pumps",
    "4140": "Fans, Air Circulators, and Blower Equipment",
    "4210": "Fire Fighting Equipment",
    "4220": "Marine Lifesaving and Diving Equipment",
    "4230": "Decontaminating and Impregnating Equipment",
    "4235": "Hazardous Material Spill Containment and Cleanup",
    "4240": "Safety and Rescue Equipment",
    "4310": "Compressors and Vacuum Pumps",
    "4320": "Power and Hand Pumps",
    "4330": "Centrifugals, Separators, and Pressure and Vacuum Filters",
    "4410": "Industrial Boilers",
    "4420": "Heat Exchangers and Steam Condensers",
    "4430": "Industrial Furnaces, Kilns, Lehrs, and Ovens",
    "4440": "Driers, Dehydrators, and Anhydrators",
    "4460": "Air Purification Equipment",
    "4470": "Industrial Pollution Control Equipment",
    "4510": "Plumbing Fixtures and Accessories",
    "4520": "Space Heating Equipment and Domestic Water Heaters",
    "4530": "Fuel Burning Equipment Units",
    "4540": "Miscellaneous Plumbing, Heating, and Sanitation Equipment",
    "4610": "Water Purification Equipment",
    "4620": "Water Distillation Equipment, Marine and Industrial",
    "4630": "Sewage Treatment Equipment",
    "4710": "Pipe, Tubing, and Hose",
    "4720": "Hose and Tubing, Flexible",
    "4730": "Fittings and Specialties: Hose, Pipe, and Tube",
    "4810": "Valves, Powered",
    "4820": "Valves, Nonpowered",
    "4910": "Motor Vehicle Maintenance and Repair Shop Specialized Equipment",
    "4920": "Aircraft Maintenance and Repair Shop Specialized Equipment",
    "4921": "Torpedo Maintenance, Repair, and Checkout Specialized Equipment",
    "4925": "Ammunition Maintenance, Repair, and Checkout Specialized Equipment",
    "4927": "Rocket Maintenance, Repair, and Checkout Specialized Equipment",
    "4930": "Lubrication and Fuel Dispensing Equipment",
    "4931": "Fire Control Maintenance and Repair Shop Specialized Equipment",
    "4933": "Weapons Maintenance and Repair Shop Specialized Equipment",
    "4935": "Guided Missile Maintenance, Repair, and Checkout Equipment",
    "4940": "Miscellaneous Maintenance and Repair Shop Specialized Equipment",
    "4960": "Space Vehicle Maintenance, Repair, and Checkout Equipment",
    "5110": "Hand Tools, Edged, Nonpowered",
    "5120": "Hand Tools, Nonedged, Nonpowered",
    "5130": "Hand Tools, Power Driven",
    "5133": "Drill Bits, Counterbores, and Countersinks: Hand and Machine",
    "5136": "Taps, Dies, and Collets: Hand and Machine",
    "5140": "Tool and Hardware Boxes",
    "5180": "Sets, Kits, and Outfits of Hand Tools",
    "5210": "Measuring Tools, Craftsmen's",
    "5220": "Inspection Gages and Precision Layout Tools",
    "5280": "Sets, Kits, and Outfits of Measuring Tools",
    "5305": "Screws",
    "5306": "Bolts",
    "5307": "Studs",
    "5310": "Nuts and Washers",
    "5315": "Nails, Machine Keys, and Pins",
    "5320": "Rivets",
    "5325": "Fastening Devices",
    "5330": "Packing and Gasket Materials",
    "5331": "O-Ring Seals",
    "5335": "Metal Screening",
    "5340": "Miscellaneous Hardware",
    "5341": "Brackets",
    "5342": "Hardware, Commercial",
    "5345": "Disks and Stones, Abrasive",
    "5350": "Abrasive Materials",
    "5355": "Knobs and Pointers",
    "5360": "Coil, Flat, and Wire Springs",
    "5365": "Rings, Shims, and Spacers",
    "5410": "Prefabricated and Portable Buildings",
    "5411": "Rigid Wall Shelters",
    "5419": "Collective Modular Support System",
    "5420": "Bridges, Fixed and Floating",
    "5430": "Storage Tanks",
    "5440": "Scaffolding Equipment and Concrete Forms",
    "5445": "Prefabricated Tower Structures",
    "5450": "Miscellaneous Prefabricated Structures",
    "5510": "Lumber and Related Basic Wood Materials",
    "5520": "Millwork",
    "5530": "Plywood and Veneer",
    "5610": "Minerals, Natural and Synthetic",
    "5620": "Tile, Brick, and Block",
    "5630": "Pipe and Conduit, Nonmetallic",
    "5640": "Wallboard, Building Paper, and Thermal Insulation Materials",
    "5650": "Roofing and Siding Materials",
    "5660": "Fencing, Fences, and Gates",
    "5670": "Architectural and Related Metal Products",
    "5680": "Miscellaneous Construction Materials",
    "5805": "Telephone and Telegraph Equipment",
    "5810": "Communications Security Equipment and Components",
    "5811": "Other Cryptologic Equipment and Components",
    "5815": "Teletype and Facsimile Equipment",
    "5820": "Radio and Television Communication Equipment, except Airborne",
    "5821": "Radio and Television Communication Equipment, Airborne",
    "5825": "Radio Navigation Equipment, except Airborne",
    "5826": "Radio Navigation Equipment, Airborne",
    "5830": "Intercommunication and Public Address Systems",
    "5831": "Video Recording and Reproducing Equipment",
    "5835": "Sound Recording and Reproducing Equipment",
    "5836": "Video Equipment",
    "5840": "Radar Equipment, except Airborne",
    "5841": "Radar Equipment, Airborne",
    "5845": "Underwater Sound Equipment",
    "5850": "Visible and Invisible Light Communication Equipment",
    "5855": "Night Vision Equipment, Emitted and Reflected Radiation",
    "5860": "Stimulated Coherent Radiation Devices, Components, and Accessories",
    "5865": "Electronic Countermeasures, Counter-Countermeasures Equipment",
    "5895": "Miscellaneous Communication Equipment",
    "5905": "Resistors",
    "5910": "Capacitors",
    "5915": "Filters and Networks",
    "5920": "Fuses, Arrestors, Absorbers, and Protectors",
    "5925": "Circuit Breakers",
    "5930": "Switches",
    "5935": "Connectors, Electrical",
    "5940": "Lugs, Terminals, and Terminal Strips",
    "5945": "Relays and Solenoids",
    "5950": "Coils and Transformers",
    "5955": "Piezoelectric Crystals",
    "5960": "Electron Tubes and Associated Hardware",
    "5961": "Semiconductor Devices and Associated Hardware",
    "5962": "Microcircuits, Electronic",
    "5963": "Electronic Modules",
    "5965": "Headsets, Handsets, Microphones, and Speakers",
    "5970": "Electrical Insulators and Insulating Materials",
    "5975": "Electrical Hardware and Supplies",
    "5977": "Electrical Contact Brushes and Electrodes",
    "5980": "Optoelectronic Devices and Associated Hardware",
    "5985": "Antennas, Waveguides, and Related Equipment",
    "5990": "Synchros and Resolvers",
    "5995": "Cable, Cord, and Wire Assemblies: Communication Equipment",
    "5998": "Electrical and Electronic Assemblies, Boards, Cards, and Associated Hardware",
    "5999": "Miscellaneous Electrical and Electronic Components",
    "6010": "Fiber Optic Conductors",
    "6015": "Fiber Optic Cables",
    "6020": "Fiber Optic Cable Assemblies and Harnesses",
    "6021": "Fiber Optic Switches",
    "6030": "Fiber Optic Devices",
    "6032": "Fiber Optic Light Sources and Photo Detectors",
    "6035": "Fiber Optic Light Transfer and Image Transfer Devices",
    "6060": "Fiber Optic Interconnectors",
    "6070": "Fiber Optic Accessories and Supplies",
    "6080": "Fiber Optic Kits and Sets",
    "6099": "Miscellaneous Fiber Optic Components",
    "6105": "Motors, Electrical",
    "6110": "Electrical Control Equipment",
    "6115": "Generators and Generator Sets, Electrical",
    "6120": "Transformers: Distribution and Power Station",
    "6125": "Converters, Electrical, Rotating",
    "6130": "Converters, Electrical, Nonrotating",
    "6135": "Batteries, Nonrechargeable",
    "6140": "Batteries, Rechargeable",
    "6145": "Wire and Cable, Electrical",
    "6150": "Miscellaneous Electric Power and Distribution Equipment",
    "6210": "Indoor and Outdoor Electric Lighting Fixtures",
    "6220": "Vehicle Lighting Equipment",
    "6230": "Electric Portable and Hand Lighting Equipment",
    "6240": "Electric Lamps",
    "6250": "Ballasts, Lampholders, and Starters",
    "6260": "Nonelectrical Lighting Equipment",
    "6310": "Traffic and Transit Signal Systems",
    "6320": "Shipboard Alarm and Signal Systems",
    "6340": "Aircraft Alarm and Signal Systems",
    "6350": "Miscellaneous Alarm, Signal, and Security Detection Systems",
    "6505": "Drugs and Biologicals",
    "6508": "Medicated Cosmetics and Toiletries",
    "6510": "Surgical Dressing Materials",
    "6515": "Medical and Surgical Instruments, Equipment, and Supplies",
    "6520": "Dental Instruments, Equipment, and Supplies",
    "6525": "X-Ray Equipment and Supplies: Medical, Dental, Veterinary",
    "6530": "Hospital Furniture, Equipment, Utensils, and Supplies",
    "6532": "Hospital and Surgical Clothing and Related Special Purpose Items",
    "6540": "Ophthalmic Instruments, Equipment, and Supplies",
    "6545": "Replenishable Field Medical Sets, Kits, and Outfits",
    "6550": "In Vitro Diagnostic Substances, Reagents, Test Kits",
    "6605": "Navigational Instruments",
    "6610": "Flight Instruments",
    "6615": "Automatic Pilot Mechanisms and Airborne Gyro Components",
    "6620": "Engine Instruments",
    "6625": "Electrical and Electronic Properties Measuring and Testing Instruments",
    "6630": "Chemical Analysis Instruments",
    "6635": "Physical Properties Testing and Inspection Equipment",
    "6636": "Environmental Chambers and Related Equipment",
    "6640": "Laboratory Equipment and Supplies",
    "6645": "Time Measuring Instruments",
    "6650": "Optical Instruments, Test Equipment, Components, and Accessories",
    "6655": "Geophysical Instruments",
    "6660": "Meteorological Instruments and Apparatus",
    "6665": "Hazard-Detecting Instruments and Apparatus",
    "6670": "Scales and Balances",
    "6675": "Drafting, Surveying, and Mapping Instruments",
    "6680": "Liquid and Gas Flow, Liquid Level, and Mechanical Motion Measuring Instruments",
    "6685": "Pressure, Temperature, and Humidity Measuring and Controlling Instruments",
    "6695": "Combination and Miscellaneous Instruments",
    "6710": "Cameras, Motion Picture",
    "6720": "Cameras, Still Picture",
    "6730": "Photographic Projection Equipment",
    "6740": "Photographic Developing and Finishing Equipment",
    "6750": "Photographic Supplies",
    "6760": "Photographic Equipment and Accessories",
    "6770": "Film, Processed",
    "6780": "Photographic Sets, Kits, and Outfits",
    "6810": "Chemicals",
    "6820": "Dyes",
    "6830": "Gases: Compressed and Liquefied",
    "6840": "Pest Control Agents and Disinfectants",
    "6850": "Miscellaneous Chemical Specialties",
    "6910": "Training Aids",
    "6920": "Armament Training Devices",
    "6930": "Operation Training Devices",
    "6940": "Communication Training Devices",
    "7010": "ADPE System Configuration",
    "7020": "ADP Central Processing Unit (CPU, Computer)",
    "7021": "ADP Input/Output and Storage Devices",
    "7022": "ADP Software",
    "7025": "ADP Input/Output and Storage Devices",
    "7030": "ADP Software",
    "7035": "ADP Support Equipment",
    "7042": "Mini and Micro Computer Control Devices",
    "7045": "ADP Supplies",
    "7050": "ADP Components",
    "7105": "Household Furniture",
    "7110": "Office Furniture",
    "7125": "Cabinets, Lockers, Bins, and Shelving",
    "7195": "Miscellaneous Furniture and Fixtures",
    "7210": "Household Furnishings",
    "7220": "Floor Coverings",
    "7230": "Draperies, Awnings, and Shades",
    "7240": "Household and Commercial Utility Containers",
    "7290": "Miscellaneous Household and Commercial Furnishings and Appliances",
    "7310": "Food Cooking, Baking, and Serving Equipment",
    "7320": "Kitchen Equipment and Appliances",
    "7330": "Kitchen Hand Tools and Utensils",
    "7340": "Cutlery and Flatware",
    "7350": "Tableware",
    "7360": "Sets, Kits, Outfits, and Modules, Food Preparation and Serving",
    "7410": "Punched Card Equipment",
    "7420": "Accounting and Calculating Machines",
    "7430": "Typewriters and Office-Type Composing Machines",
    "7435": "Office Information System Equipment",
    "7450": "Office-Type Sound Recording and Reproducing Machines",
    "7460": "Visible Record Equipment",
    "7490": "Miscellaneous Office Machines",
    "7510": "Office Supplies",
    "7520": "Office Devices and Accessories",
    "7530": "Stationery and Record Forms",
    "7610": "Books and Pamphlets",
    "7630": "Newspapers and Periodicals",
    "7640": "Maps, Atlases, Charts, and Globes",
    "7650": "Drawings and Specifications",
    "7660": "Sheet and Book Music",
    "7670": "Microfilm, Processed",
    "7690": "Miscellaneous Printed Matter",
    "7710": "Musical Instruments",
    "7720": "Musical Instrument Parts and Accessories",
    "7730": "Phonographs, Radios, and Television Sets: Home Type",
    "7810": "Athletic and Sporting Equipment",
    "7820": "Games, Toys, and Wheeled Goods",
    "7830": "Recreational and Gymnastic Equipment",
    "7910": "Floor Polishers and Vacuum Cleaning Equipment",
    "7920": "Brooms, Brushes, Mops, and Sponges",
    "7930": "Cleaning and Polishing Compounds and Preparations",
    "8010": "Paints, Dopes, Varnishes, and Related Products",
    "8020": "Paint and Artists' Brushes",
    "8030": "Preservative and Sealing Compounds",
    "8040": "Adhesives",
    "8105": "Bags and Sacks",
    "8110": "Drums and Cans",
    "8115": "Boxes, Cartons, and Crates",
    "8120": "Commercial and Industrial Gas Cylinders",
    "8125": "Bottles and Jars",
    "8130": "Reels and Spools",
    "8135": "Packaging and Packing Bulk Materials",
    "8140": "Ammunition and Nuclear Ordnance Boxes, Packages, Special Containers",
    "8145": "Specialized Shipping and Storage Containers",
    "8150": "Freight Containers",
    "8305": "Textile Fabrics",
    "8310": "Yarn and Thread",
    "8315": "Notions and Apparel Findings",
    "8320": "Padding and Stuffing Materials",
    "8325": "Fur Materials",
    "8330": "Leather",
    "8335": "Shoe Findings and Soling Materials",
    "8340": "Tents and Tarpaulins",
    "8345": "Flags and Pennants",
    "8405": "Outerwear, Men's",
    "8410": "Outerwear, Women's",
    "8415": "Clothing, Special Purpose",
    "8420": "Underwear and Nightwear, Men's",
    "8425": "Underwear and Nightwear, Women's",
    "8430": "Footwear, Men's",
    "8435": "Footwear, Women's",
    "8440": "Hosiery, Handwear, and Clothing Accessories, Men's",
    "8445": "Hosiery, Handwear, and Clothing Accessories, Women's",
    "8450": "Children's and Infants' Apparel and Accessories",
    "8455": "Badges and Insignia",
    "8460": "Luggage",
    "8465": "Individual Equipment",
    "8470": "Armor, Personal",
    "8475": "Specialized Flight Clothing and Accessories",
    "8510": "Toiletry Paper Products",
    "8520": "Toilet Soap, Shaving Preparations, and Dentifrices",
    "8530": "Personal Toiletry Articles",
    "8540": "Toiletry Appliances, Razors, and Related Products",
    "8710": "Forage and Feed",
    "8720": "Fertilizers",
    "8730": "Seeds and Nursery Stock",
    "8810": "Live Animals, Raised for Food",
    "8820": "Live Animals, Not Raised for Food",
    "8905": "Meats, Poultry, and Fish",
    "8910": "Dairy Foods and Eggs",
    "8915": "Fruits and Vegetables",
    "8920": "Bakery and Cereal Products",
    "8925": "Sugar, Confectionery, and Nuts",
    "8930": "Jams, Jellies, and Preserves",
    "8935": "Soups and Bouillons",
    "8940": "Special Dietary Foods and Food Specialty Preparations",
    "8945": "Food Oils and Fats",
    "8950": "Condiments and Related Products",
    "8955": "Coffee, Tea, and Cocoa",
    "8960": "Beverages, Nonalcoholic",
    "8965": "Beverages, Alcoholic",
    "8970": "Composite Food Packages",
    "8975": "Tobacco Products",
    "9110": "Fuels, Solid",
    "9130": "Liquid Propellants and Fuels, Petroleum Base",
    "9135": "Liquid Propellant Fuels and Oxidizers, Chemical Base",
    "9140": "Fuel Oils",
    "9150": "Oils and Greases: Cutting, Lubricating, and Hydraulic",
    "9160": "Miscellaneous Waxes, Oils, and Fats",
    "9310": "Paper and Paperboard",
    "9320": "Rubber Fabricated Materials",
    "9330": "Plastics Fabricated Materials",
    "9340": "Glass Fabricated Materials",
    "9350": "Refractories and Fire Surfacing Materials",
    "9390": "Miscellaneous Fabricated Nonmetallic Materials",
    "9410": "Crude Grades of Plant Materials",
    "9420": "Fibers: Vegetable, Animal, and Synthetic",
    "9430": "Miscellaneous Crude Animal Products, Inedible",
    "9440": "Miscellaneous Crude Agricultural and Forestry Products",
    "9450": "Miscellaneous Crude Nonmetallic Minerals",
    "9505": "Wire, Nonelectrical, Iron and Steel",
    "9510": "Bars and Rods, Iron and Steel",
    "9515": "Plate, Sheet, Strip, Foil, and Leaf: Iron and Steel",
    "9520": "Structural Shapes, Iron and Steel",
    "9525": "Wire, Nonelectrical, Nonferrous Base Metal",
    "9530": "Bars and Rods, Nonferrous Base Metal",
    "9535": "Plate, Sheet, Strip, Foil, and Leaf: Nonferrous Base Metal",
    "9540": "Structural Shapes, Nonferrous Base Metal",
    "9545": "Plate, Sheet, Strip, Foil, and Leaf: Precious Metal",
    "9610": "Ores",
    "9620": "Minerals, Natural and Synthetic",
    "9630": "Additive Metal Materials and Master Alloys",
    "9640": "Iron and Steel Primary and Semifinished Products",
    "9650": "Nonferrous Base Metal Refinery and Intermediate Forms",
    "9660": "Precious Metals Primary Forms",
    "9670": "Iron and Steel Scrap",
    "9680": "Nonferrous Metal Scrap",
    "9905": "Signs, Advertising Displays, and Identification Plates",
    "9910": "Jewelry",
    "9915": "Collectors' Items",
    "9920": "Smokers' Articles and Matches",
    "9925": "Ecclesiastical Equipment, Furnishings, and Supplies",
    "9930": "Memorial and Mortuary Supplies",
    "9999": "Miscellaneous Items",
}


class Command(BaseCommand):
    help = "Populate FSC name and group_name from federal reference data"

    def handle(self, *args, **options):
        updated = 0
        created_groups = 0

        for fsc in FederalSupplyClass.objects.all():
            changed = False
            group = fsc.code[:2]

            # Update group field if needed
            if fsc.group != group:
                fsc.group = group
                changed = True

            # Update group_name
            group_name = FSG_NAMES.get(group, "")
            if group_name and fsc.group_name != group_name:
                fsc.group_name = group_name
                changed = True
                created_groups += 1

            # Update name
            name = FSC_NAMES.get(fsc.code, "")
            if name and (not fsc.name or fsc.name == "General Products"):
                fsc.name = name
                changed = True

            if changed:
                fsc.save()
                updated += 1

        self.stdout.write(self.style.SUCCESS(
            f"Updated {updated} FSC records, {created_groups} group names set"
        ))
